"""
Markdown Report Generator
Produces a Markdown report from scan findings
"""

from datetime import datetime
from pathlib import Path
from typing import List

from smuggler.scanner.core import ScanResult
from smuggler.scanner.detectors import Finding, Confidence
from smuggler import __version__


CONFIDENCE_LABEL = {
    Confidence.CONFIRMED: "Confirmed",
    Confidence.LIKELY: "Likely",
    Confidence.POSSIBLE: "Possible",
    Confidence.FALSE_POS: "False Positive",
}

SEVERITY_BADGE = {
    "critical": "CRITICAL",
    "high": "HIGH",
    "medium": "MEDIUM",
    "low": "LOW",
}


def _finding_row(f: Finding) -> str:
    badge = SEVERITY_BADGE.get(f.severity, f.severity.upper())
    conf = CONFIDENCE_LABEL.get(f.confidence, f.confidence.value)
    refs = ""
    if f.references:
        refs = "\n".join(f"  - {r}" for r in f.references)

    return f"""### [{badge}] {f.payload_name}

| Field | Value |
|-------|-------|
| Technique | `{f.technique}` |
| Severity | **{f.severity.upper()}** |
| Confidence | {conf} |
| Elapsed | {f.elapsed:.2f}s |

**Description:** {f.description}

**Evidence:** `{f.evidence}`

""" + (f"**Remediation:** {f.remediation}\n\n" if f.remediation else "") + \
     (f"**References:**\n{refs}\n" if refs else "")


def generate_markdown(results: List[ScanResult], output_dir: str) -> str:
    """Generate a Markdown report from scan results. Returns the file path."""
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = out_dir / f"smuggler_report_{timestamp}.md"

    total_targets = len(results)
    vulnerable = sum(1 for r in results if r.is_vulnerable)
    critical_count = sum(r.critical_count for r in results)
    high_count = sum(r.high_count for r in results)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f"# HTTP Request Smuggler Report",
        "",
        f"Generated: {ts}  ",
        f"Version: {__version__}",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Metric | Count |",
        f"|--------|------:|",
        f"| Targets scanned | {total_targets} |",
        f"| Vulnerable | {vulnerable} |",
        f"| Critical | {critical_count} |",
        f"| High | {high_count} |",
        "",
    ]

    for r in results:
        status = "VULNERABLE" if r.is_vulnerable else "CLEAN"
        lines.append("---")
        lines.append("")
        lines.append(f"## {r.target} [{status}]")
        lines.append("")

        if r.target_info:
            ti = r.target_info
            lines.append("| Property | Value |")
            lines.append("|----------|-------|")
            lines.append(f"| WAF/CDN | {ti.waf or 'None detected'} |")
            lines.append(f"| Backend | {ti.backend or 'Unknown'} |")
            lines.append(f"| HTTP/2 | {'Yes' if ti.supports_h2 else 'No'} |")
            lines.append(f"| Baseline RTT | {ti.baseline_time:.3f}s |")
            lines.append(f"| Requests sent | {r.total_requests} |")
            lines.append(f"| Techniques | {', '.join(r.techniques_tested)} |")
            lines.append("")

        if r.findings:
            lines.append(f"### Findings ({len(r.findings)})")
            lines.append("")
            for f in r.findings:
                lines.append(_finding_row(f))
        else:
            lines.append("*No vulnerabilities detected for this target.*")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by HTTP Request Smuggler -- For authorized security testing only*")
    lines.append("")

    content = "\n".join(lines)

    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)

    return str(filename)
